import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,X,Phone,Mail,MapPin,Bus,BookOpen,GraduationCap,HeartHandshake,ShieldCheck,Microscope,Monitor,Music,Palette,Trophy,Users,CalendarDays,Image as ImageIcon,ArrowRight,LockKeyhole,LogOut,Save,Plus,Trash2,Edit3,Upload,ChevronLeft,ChevronRight,ExternalLink,School,FlaskConical,Calculator,Gamepad2,Building2,Camera,Newspaper,Settings,Star,CheckCircle2} from 'lucide-react';
import './styles.css';

const SCHOOL={name:'Sri Vidya E.M. School',te:'శ్రీ విద్యా ఇ.ఎం. స్కూల్',est:'2002',phone:'9491171564',email:'babjivelavalapalli@gmail.com',address:'Sri Vidya E.M. School, Kesavaram, Ganapavaram Mandal, West Godavari District, Andhra Pradesh - 534186',place:'Kesavaram, West Godavari',principal:'Velavalapalli Babji'};
const defaultData={
 academics:[
  ['LKG & UKG','Foundational Learning','Age-appropriate foundational learning, language development, numbers, creative expression and school readiness.','Early Years','/images/items/lkg-ukg.svg',GraduationCap],
  ['Primary 1–5','Strong Foundations','Strong academic foundations with active participation, practice and confidence-building learning.','Foundation','/images/items/primary-1-5.svg',BookOpen],
  ['6th & 7th Class','State Syllabus','English Medium education following the State Syllabus for 6th and 7th Classes.','State Syllabus','/images/items/6th-7th-class.svg',School],
  ['English Medium','Communication','English Medium learning with opportunities for students to communicate and participate confidently.','Medium','/images/items/english-medium.svg',Users],
  ['Digital Learning','Technology Support','Technology-supported teaching and visual learning resources for engaging lessons.','Digital','/images/items/digital-learning.svg',Monitor],
  ['Assessment & Support','Learner Progress','Regular learning activities, practice, feedback and individual academic support.','Progress','/images/items/assessment-support.svg',CheckCircle2]
 ],
 facilities:[
  ['Smart Classrooms','Interactive, technology-supported classroom learning.','https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=85',Monitor],['Computer Lab','A dedicated environment for computer-based learning.','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=85',Monitor],['Science Lab','A space for science learning, observation and discovery.','https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1000&q=85',FlaskConical],['Mathematics Lab','Activity-oriented mathematics learning and practice.','https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1000&q=85',Calculator],['Library','Reading, reference and independent learning environment.','https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1000&q=85',BookOpen],['Playground','Outdoor play, physical activity and sports participation.','https://images.unsplash.com/photo-1526634332515-d56c0f7f2d07?auto=format&fit=crop&w=1000&q=85',Trophy],['Indoor Games','Indoor recreation and games for students.','https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=85',Gamepad2],['Auditorium','School programmes, cultural events and presentations.','https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1000&q=85',Building2],['Transport','School Bus and Van Service available for students.','https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=85',Bus],['CCTV Security','CCTV-supported campus safety and supervision.','https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1000&q=85',ShieldCheck],['RO Drinking Water','RO drinking water facility available at school.','https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=1000&q=85',ShieldCheck],['Canteen','School canteen facility for students.','https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1000&q=85',HeartHandshake],['Medical Room','A designated medical support room.','https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1000&q=85',HeartHandshake],['Activity Rooms','Dedicated spaces for student activities.','https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=1000&q=85',Palette],['Music / Dance','Music and dance activities and programmes.','https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1000&q=85',Music],['Other Facilities','Other supporting facilities available at school.','https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=85',Star]
 ],
 activities:[
  ['Sports','Sports participation, physical activity and healthy competition.','https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=85',Trophy],['Cultural Programs','Cultural programmes and creative stage presentations.','https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1000&q=85',Music],['Annual Day','Annual Day programmes and student participation.','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=85',CalendarDays],['Sports Day','Sports Day events and student participation.','https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=85',Trophy],['Science Exhibition','Science Exhibition activities and student projects.','https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1000&q=85',FlaskConical],['Educational Tours','Educational tours and learning beyond the classroom.','https://images.unsplash.com/photo-1503220317375-aaad61436b1b?auto=format&fit=crop&w=1000&q=85',Bus],['Yoga','Yoga and wellness-oriented student activities.','https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1000&q=85',HeartHandshake],['Dance','Dance activities and creative expression.','https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1000&q=85',Music],['Music','Music activities and performances.','https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1000&q=85',Music],['Drawing','Drawing, colouring and visual creativity.','https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=85',Palette],['Clubs','Student clubs and participation activities.','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=85',Users],['Celebrations','School celebrations and special-day programmes.','https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=85',Star]
 ],
 gallery:[
  {src:'/images/campus-original.jpeg',title:'School Campus',cat:'Campus'},
  {src:'/images/principal-designed.png',title:'Principal',cat:'Principal'},
  {src:'/images/event-group-1.jpeg',title:'School Event',cat:'Events'},
  {src:'/images/event-group-2.jpeg',title:'Student Activity',cat:'Activities'},
  {src:'/images/event-portrait.jpeg',title:'School Programme',cat:'Events'},
  {src:'/images/event-celebration.png',title:'Celebration',cat:'Celebrations'},
  {src:'/images/staff-group.png',title:'School Team',cat:'Activities'}
 ],
 news:[]
};
const teNav={Home:'హోమ్',About:'మా గురించి',Academics:'విద్యా విభాగాలు',Facilities:'సౌకర్యాలు',Activities:'కార్యక్రమాలు',Admissions:'అడ్మిషన్స్',Gallery:'గ్యాలరీ',News:'వార్తలు',Contact:'సంప్రదించండి'};
const labels={en:{about:'ABOUT THE SCHOOL',academics:'ACADEMICS',facilities:'FACILITIES',activities:'ACTIVITIES',principal:'PRINCIPAL',campus:'SCHOOL CAMPUS',gallery:'GALLERY',news:'NEWS & EVENTS',admissions:'ADMISSIONS',contact:'CONTACT'},te:{about:'పాఠశాల గురించి',academics:'విద్యా విభాగాలు',facilities:'సౌకర్యాలు',activities:'కార్యక్రమాలు',principal:'ప్రధానోపాధ్యాయులు',campus:'పాఠశాల ప్రాంగణం',gallery:'గ్యాలరీ',news:'వార్తలు & కార్యక్రమాలు',admissions:'అడ్మిషన్స్',contact:'సంప్రదించండి'}};
function normalizeRemoteData(remote){
 const base={...defaultData,...remote};
 const withIcons=(section,fallback)=> (Array.isArray(base[section])&&base[section].length?base[section]:fallback).map((x,i)=>{
  const def=fallback[i];
  if(Array.isArray(x)){const out=[...x]; if(section!=='gallery' && out.length>=4) out[out.length-1]=out[out.length-1]||def?.[def.length-1]||Star; return out;}
  return x;
 });
 return {...base,academics:withIcons('academics',defaultData.academics),facilities:withIcons('facilities',defaultData.facilities),activities:withIcons('activities',defaultData.activities),gallery:Array.isArray(base.gallery)?base.gallery:defaultData.gallery,news:Array.isArray(base.news)?base.news:defaultData.news};
}
function stripForApi(data){
 const clean={...data};
 for(const section of ['academics','facilities','activities']) clean[section]=(data[section]||[]).map(x=>Array.isArray(x)?x.slice(0,-1):x);
 return clean;
}
function useStore(){
 const [d,setD]=useState(defaultData);
 const [ready,setReady]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{try{const r=await fetch('/api/cms',{cache:'no-store'});if(r.ok){const remote=await r.json();if(!cancelled)setD(normalizeRemoteData(remote));}}catch(e){console.warn('CMS API unavailable; using bundled data',e)}finally{if(!cancelled)setReady(true)}})();return()=>{cancelled=true}},[]);
 return [d,setD,ready];
}
async function cmsSave(data){
 const token=sessionStorage.getItem('sv-cms-token');
 const r=await fetch('/api/cms',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token||''}`},body:JSON.stringify(stripForApi(data))});
 if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.error||'Could not save CMS data')}
 return normalizeRemoteData(await r.json());
}
async function cmsLogin(username,password){
 const r=await fetch('/api/cms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});
 const data=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(data.error||'Invalid admin credentials');
 sessionStorage.setItem('sv-cms-token',data.token);return true;
}
async function cmsUpload(file){
 const token=sessionStorage.getItem('sv-cms-token');
 const r=await fetch('/api/upload',{method:'POST',headers:{Authorization:`Bearer ${token||''}`,'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});
 const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Image upload failed');return data.url;
}

class ErrorBoundary extends React.Component{state={error:null};static getDerivedStateFromError(error){return {error}};componentDidCatch(error,info){console.error('Sri Vidya website runtime error:',error,info)}render(){if(this.state.error)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:30,fontFamily:'system-ui',background:'#f5f8fc',color:'#082b59'}}><div style={{maxWidth:700,background:'#fff',padding:30,borderRadius:20,boxShadow:'0 20px 60px rgba(0,0,0,.12)'}}><h2>Website loading error</h2><p>The Sri Vidya E.M. School website encountered a runtime error.</p><pre style={{whiteSpace:'pre-wrap',color:'#9b1c1c',fontSize:12}}>{String(this.state.error?.stack||this.state.error)}</pre><button onClick={()=>location.reload()} style={{padding:'10px 16px',border:0,borderRadius:10,background:'#0877db',color:'#fff'}}>Reload website</button></div></div>;return this.props.children}}
function SectionHead({num,k,teTitle}){return <div className="section-head"><span>{num}</span><div><div className="eyebrow">{k}</div><h2>{teTitle}</h2></div></div>}
function Feature({item,i}){const [title,sub,desc,tag,img,Icon]=item;const SafeIcon=Icon||GraduationCap;return <article className="feature-card reveal" style={{'--i':i}}><div className="feature-image"><img src={img||'/images/items/placeholder.svg'} alt={title}/></div><div className="feature-icon"><SafeIcon size={28}/></div><div><span className="tag">{tag}</span><h3>{title}</h3><h4>{sub}</h4><p>{desc}</p></div></article>}
function VisualCard({item,i}){const [title,desc,img,Icon]=item;const SafeIcon=Icon||Star;return <article className="visual-card reveal" style={{'--i':i}}><div className="visual-art"><img src={img||'/images/items/placeholder.svg'} alt={title}/><div className="art-overlay"></div><div className="art-orb"></div><div className="icon-box"><SafeIcon size={31}/></div><span>SV</span></div><div className="vbody"><h3>{title}</h3><p>{desc}</p><a href="#contact">Learn more <ArrowRight size={15}/></a></div></article>}
function Admin({d,setD,onClose}){
 const [logged,setLogged]=useState(!!sessionStorage.getItem('sv-cms-token')),[u,setU]=useState(''),[p,setP]=useState(''),[tab,setTab]=useState('home'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const save=async(next)=>{setD(next);setBusy(true);try{const saved=await cmsSave(next);setD(saved);setMsg('Saved to live CMS');setTimeout(()=>setMsg(''),1600)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const upload=async(file,section,key,index)=>{if(!file)return;setBusy(true);try{const url=await cmsUpload(file);const next={...d};if(section==='gallery'){next.gallery=[...(d.gallery||[]),{src:url,title:file.name.replace(/\.[^.]+$/, ''),cat:'School'}]}else if(index!==undefined){next[section]=d[section].map((x,i)=>i===index?(Array.isArray(x)?x.map((v,j)=>j===key?url:v):{...x,[key]:url}):x)}else next[key]=url;await save(next)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const edit=(section,index,key,value)=>save({...d,[section]:d[section].map((x,i)=>i===index?(Array.isArray(x)?x.map((v,j)=>j===key?value:v):{...x,[key]:value}):x)});
 const remove=async(section,index)=>{if(!confirm('Delete this item?'))return;try{if(section==='gallery'&&d.gallery[index]?.src?.startsWith('https://')){const token=sessionStorage.getItem('sv-cms-token');await fetch('/api/upload',{method:'DELETE',headers:{Authorization:`Bearer ${token||''}`,'X-Blob-Url':d.gallery[index].src}})}await save({...d,[section]:d[section].filter((_,i)=>i!==index)})}catch(e){setMsg(e.message)}};
 const add=(section,item)=>save({...d,[section]:[...(d[section]||[]),item]});
 const login=async()=>{setBusy(true);try{await cmsLogin(u,p);setLogged(true);setMsg('Admin login successful')}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 if(!logged)return <div className="modal"><div className="modal-box login"><button className="close" onClick={onClose}><X/></button><div className="admin-brand"><LockKeyhole/><div><b>Admin CMS</b><small>Sri Vidya E.M. School</small></div></div><input placeholder="Username" value={u} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Password" value={p} onChange={e=>setP(e.target.value)}/><button className="btn primary full" disabled={busy} onClick={login}>{busy?'Signing in…':'Login'} <ArrowRight size={16}/></button><small>Use the production credentials configured in Vercel.</small>{msg&&<div className="error">{msg}</div>}</div></div>;
 const tabs=[['home','Home'],['principal','Principal'],['academics','Academics'],['facilities','Facilities'],['activities','Activities'],['transport','Transport'],['gallery','Gallery'],['news','News & Events'],['contact','Contact'],['seo','SEO']];
 const listEditor=(section,kind)=> <div className="admin-content"><div className="admin-list">{(d[section]||[]).map((x,i)=>{const a=Array.isArray(x)?x:null;return <div className="admin-row" key={i}><div className="row-fields">{kind==='academic'?<><input value={a?.[0]||''} onChange={e=>edit(section,i,0,e.target.value)} placeholder="Title"/><input value={a?.[1]||''} onChange={e=>edit(section,i,1,e.target.value)} placeholder="Subtitle"/><textarea value={a?.[2]||''} onChange={e=>edit(section,i,2,e.target.value)} placeholder="Description"/><input value={a?.[3]||''} onChange={e=>edit(section,i,3,e.target.value)} placeholder="Tag"/><input value={a?.[4]||''} onChange={e=>edit(section,i,4,e.target.value)} placeholder="Image URL"/><label className="upload-box"><Upload size={15}/> Upload image<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],section,4,i)}/></label></>:<><input value={a?.[0]||''} onChange={e=>edit(section,i,0,e.target.value)} placeholder="Title"/><textarea value={a?.[1]||''} onChange={e=>edit(section,i,1,e.target.value)} placeholder="Description"/><input value={a?.[2]||''} onChange={e=>edit(section,i,2,e.target.value)} placeholder="Image URL"/><label className="upload-box"><Upload size={15}/> Upload image<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],section,2,i)}/></label></>}</div><button className="icon-danger" onClick={()=>remove(section,i)}><Trash2 size={16}/></button></div>})}</div><button className="btn primary" onClick={()=>add(section,kind==='academic'?['New Academic Item','Subtitle','Official description','Category','/images/items/placeholder.svg',GraduationCap]:['New Item','Official description','/images/items/placeholder.svg',Star])}><Plus size={16}/> Add {kind==='academic'?'academic item':'item'}</button></div>;
 return <div className="modal"><div className="modal-box admin-panel"><button className="close" onClick={onClose}><X/></button><div className="admin-top"><div><div className="eyebrow">CONTROL CENTER</div><h2>Admin CMS</h2><p>Manage the live website. Changes are saved to the production CMS.</p></div><button className="btn dark" onClick={()=>{sessionStorage.removeItem('sv-cms-token');setLogged(false)}}><LogOut size={15}/> Logout</button></div><div className="admin-tabs">{tabs.map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>{msg&&<div className="success">✓ {msg}</div>}
 {tab==='home'&&<div className="admin-content"><label>Hero Heading<input value={d.heroTitle||SCHOOL.name} onChange={e=>save({...d,heroTitle:e.target.value})}/></label><label>Hero Subtitle<input value={d.heroSub||'Established 2002 • English Medium • LKG to 7th Class'} onChange={e=>save({...d,heroSub:e.target.value})}/></label><label>About Text<textarea value={d.about||''} onChange={e=>save({...d,about:e.target.value})}/></label><label>Hero Image URL<input value={d.heroImage||'/images/hero-campus.png'} onChange={e=>save({...d,heroImage:e.target.value})}/><span className="upload-box"><Upload size={18}/> Upload Hero Image<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],null,'heroImage')}/></span></label><label>Campus Image URL<input value={d.campusImage||'/images/campus-original.jpeg'} onChange={e=>save({...d,campusImage:e.target.value})}/><span className="upload-box"><Upload size={18}/> Upload Campus Image<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],null,'campusImage')}/></span></label></div>}
 {tab==='principal'&&<div className="admin-content"><label>Principal Name<input value={d.principalName||SCHOOL.principal} onChange={e=>save({...d,principalName:e.target.value})}/></label><label>Designation<input value={d.principalRole||'Principal / Correspondent / Chairman'} onChange={e=>save({...d,principalRole:e.target.value})}/></label><label>Principal Message<textarea value={d.principalMessage||'School leadership information can be updated here.'} onChange={e=>save({...d,principalMessage:e.target.value})}/></label><label>Principal Image URL<input value={d.principalImage||'/images/principal-designed.png'} onChange={e=>save({...d,principalImage:e.target.value})}/><span className="upload-box"><Upload size={18}/> Upload Principal Photo<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],null,'principalImage')}/></span></label></div>}
 {tab==='academics'&&listEditor('academics','academic')}
 {tab==='facilities'&&listEditor('facilities','facility')}
 {tab==='activities'&&listEditor('activities','activity')}
 {tab==='transport'&&<div className="admin-content"><label>Transport Title<input value={d.transportTitle||'School Bus & Van Service'} onChange={e=>save({...d,transportTitle:e.target.value})}/></label><label>Transport Description<textarea value={d.transportDesc||'School Bus and Van Services are available for students. Contact the school for current route and transport details.'} onChange={e=>save({...d,transportDesc:e.target.value})}/></label><label>Bus Details<textarea value={d.busDetails||'School Bus Service available.'} onChange={e=>save({...d,busDetails:e.target.value})}/></label><label>Van Details<textarea value={d.vanDetails||'School Van Service available.'} onChange={e=>save({...d,vanDetails:e.target.value})}/></label></div>}
 {tab==='gallery'&&<div className="admin-content"><div className="empty-admin">Gallery changes are live. Uploads are stored in Vercel Blob and can be managed from this panel.</div><label className="upload-box"><Upload size={20}/> Upload Gallery Image<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0],'gallery')}/></label>{(d.gallery||[]).map((x,i)=><div className="admin-row" key={i}><div className="row-fields"><input value={x.title||''} onChange={e=>edit('gallery',i,'title',e.target.value)} placeholder="Title"/><input value={x.cat||''} onChange={e=>edit('gallery',i,'cat',e.target.value)} placeholder="Category"/><input value={x.src||''} onChange={e=>edit('gallery',i,'src',e.target.value)} placeholder="Image path"/></div><button className="icon-danger" onClick={()=>remove('gallery',i)}><Trash2 size={16}/></button></div>)}<button className="btn primary" onClick={()=>add('gallery',{src:'/images/items/placeholder.svg',title:'New Gallery Image',cat:'School'})}><Plus size={16}/> Add gallery item</button></div>}
 {tab==='news'&&<div className="admin-content">{(d.news||[]).map((x,i)=><div className="admin-row" key={i}><div className="row-fields"><input value={x.title||''} onChange={e=>edit('news',i,'title',e.target.value)} placeholder="Title"/><input value={x.date||''} onChange={e=>edit('news',i,'date',e.target.value)} placeholder="Date"/><textarea value={x.description||''} onChange={e=>edit('news',i,'description',e.target.value)} placeholder="Description"/></div><button className="icon-danger" onClick={()=>remove('news',i)}><Trash2 size={16}/></button></div>)}<button className="btn primary" onClick={()=>add('news',{title:'New School News',date:new Date().toISOString().slice(0,10),description:'Add official school news here.'})}><Plus size={16}/> Add news</button></div>}
 {tab==='contact'&&<div className="admin-content"><label>Phone<input value={d.phone||SCHOOL.phone} onChange={e=>save({...d,phone:e.target.value})}/></label><label>Email<input value={d.email||SCHOOL.email} onChange={e=>save({...d,email:e.target.value})}/></label><label>Address<textarea value={d.address||SCHOOL.address} onChange={e=>save({...d,address:e.target.value})}/></label><label>Google Maps URL<input value={d.mapsUrl||'https://www.google.com/maps/search/?api=1&query=Sri+Vidya+E.M.+School+Kesavaram+Andhra+Pradesh'} onChange={e=>save({...d,mapsUrl:e.target.value})}/></label></div>}
 {tab==='seo'&&<div className="admin-content"><label>SEO Title<input value={d.seoTitle||'Sri Vidya E.M. School | English Medium School in Kesavaram'} onChange={e=>save({...d,seoTitle:e.target.value})}/></label><label>Meta Description<textarea value={d.seoDesc||'Sri Vidya E.M. School, established in 2002 at Kesavaram, offers English Medium education from LKG to 7th Class.'} onChange={e=>save({...d,seoDesc:e.target.value})}/></label><label>Keywords<textarea value={d.seoKeywords||'Sri Vidya E.M. School, Kesavaram school, English Medium School, West Godavari school, LKG to 7th Class'} onChange={e=>save({...d,seoKeywords:e.target.value})}/></label></div>}
 </div></div>
}

function Gallery({items,lang}){const [cat,setCat]=useState('All'),[idx,setIdx]=useState(null);const cats=['All',...new Set(items.map(x=>x.cat))];const filtered=cat==='All'?items:items.filter(x=>x.cat===cat);return <section id="gallery" className="section gallery-section"><SectionHead num="07" k={labels[lang].gallery} teTitle={lang==='en'?'Real school moments, presented beautifully.':'పాఠశాల నిజమైన జ్ఞాపకాలను అందంగా ప్రదర్శించే గ్యాలరీ.'}/><div className="filters">{cats.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="gallery-grid">{filtered.map((x,i)=><button className="gallery-item" key={x.src+i} onClick={()=>setIdx(i)}><img src={x.src} alt={x.title}/><span>{x.title}</span></button>)}</div>{idx!==null&&<div className="lightbox" onClick={()=>setIdx(null)}><button className="lb-close"><X/></button><button className="lb-prev" onClick={e=>{e.stopPropagation();setIdx((idx-1+filtered.length)%filtered.length)}}><ChevronLeft/></button><img src={filtered[idx].src} alt={filtered[idx].title} onClick={e=>e.stopPropagation()}/><button className="lb-next" onClick={e=>{e.stopPropagation();setIdx((idx+1)%filtered.length)}}><ChevronRight/></button><div className="lb-title">{filtered[idx].title} • {idx+1}/{filtered.length}</div></div>}</section>}
function App(){const [lang,setLang]=useState('en'),[menu,setMenu]=useState(false),[admin,setAdmin]=useState(false),[d,setD,ready]=useStore();useEffect(()=>{const els=document.querySelectorAll('.reveal');if(!('IntersectionObserver' in window)){els.forEach(e=>e.classList.add('show'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.08});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[d,lang]);const nav=[['Home','#home'],['About','#about'],['Academics','#academics'],['Facilities','#facilities'],['Activities','#activities'],['Admissions','#admissions'],['Gallery','#gallery'],['News','#news'],['Contact','#contact']];const about=d.about||'Sri Vidya E.M. School was established in 2002 at Kesavaram, Ganapavaram Mandal, West Godavari District, Andhra Pradesh. The school provides English Medium education from LKG to 7th Class and follows the State Syllabus. Along with academic education, the school encourages students to participate in sports, cultural programmes, science exhibitions, educational tours, yoga, music, dance, drawing, clubs and various celebrations.';
 return <>{!ready&&<div className="cms-loading">Loading live school content…</div>}<div className="announcement"><span>✦ {lang==='en'?'Established 2002 • English Medium • LKG to 7th Class':'2002లో స్థాపించబడింది • ఆంగ్ల మాధ్యమం • LKG నుండి 7వ తరగతి'}</span><span className="ann-right"><Phone size={13}/>{d.phone||SCHOOL.phone}<button onClick={()=>setLang(lang==='en'?'te':'en')}>{lang==='en'?'తెలుగు':'English'}</button></span></div><header><a href="#home" className="brand"><img src="/images/logo.png" alt="Sri Vidya E.M. School logo"/><div><strong>{lang==='en'?SCHOOL.name:SCHOOL.te}</strong><small>KESAVARAM • EST. 2002</small></div></a><nav className={menu?'open':''}>{nav.map(([n,h])=><a href={h} key={h} onClick={()=>setMenu(false)}>{lang==='en'?n:teNav[n]}</a>)}</nav><div className="head-actions"><a className="head-call" href={'tel:'+(d.phone||SCHOOL.phone)}><Phone size={16}/>{SCHOOL.phone}</a><button className="lang-btn" onClick={()=>setLang(lang==='en'?'te':'en')}>{lang==='en'?'తె':'EN'}</button><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main><section id="home" className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(4,27,67,.9),rgba(4,27,67,.52),rgba(4,27,67,.1)),url('${d.heroImage||'/images/hero-campus.png'}')`}}><div className="hero-glow g1"></div><div className="hero-glow g2"></div><div className="hero-content"><span className="hero-kicker">✦ {lang==='en'?'KESAVARAM • WEST GODAVARI':'కేశవరం • వెస్ట్ గోదావరి'}</span><h1>{d.heroTitle||SCHOOL.name}</h1><h2>{d.heroSub||'Established 2002 • English Medium • LKG to 7th Class'}</h2><p>{lang==='en'?'A colourful learning environment where children build knowledge, confidence, values and joyful school memories.':'పిల్లలు జ్ఞానం, ఆత్మవిశ్వాసం, విలువలు మరియు ఆనందకరమైన పాఠశాల జ్ఞాపకాలను పెంపొందించుకునే రంగుల విద్యా వాతావరణం.'}</p><div className="hero-btns"><a className="btn primary" href="#admissions">{lang==='en'?'Admissions Open':'అడ్మిషన్స్'} <ArrowRight size={18}/></a><a className="btn glass" href="#about">{lang==='en'?'Explore Our School':'మా పాఠశాల గురించి'}</a></div></div><div className="hero-stats"><div><b>2002</b><span>Established</span></div><div><b>LKG–7</b><span>Classes</span></div><div><b>English</b><span>Medium</span></div><div><b>Bus + Van</b><span>Transport</span></div></div><div className="hero-badge"><School size={23}/><span>State Syllabus</span></div></section>
 <section className="highlights"><div className="highlight reveal"><span>01</span><b>English Medium</b><small>LKG to 7th Class</small></div><div className="highlight reveal"><span>02</span><b>State Syllabus</b><small>6th & 7th included</small></div><div className="highlight reveal"><span>03</span><b>Bus + Van</b><small>Transport available</small></div><div className="highlight reveal"><span>04</span><b>CCTV Security</b><small>Safety-focused campus</small></div></section>
 <section id="about" className="section about"><SectionHead num="01" k={labels[lang].about} teTitle={lang==='en'?'Education with knowledge, character & confidence.':'జ్ఞానం, వ్యక్తిత్వం, ఆత్మవిశ్వాసంతో కూడిన విద్య.'}/><div className="about-grid"><div className="about-copy"><p>{about}</p><div className="about-points"><div><CheckCircle2/><b>Established 2002</b><small>Serving the Kesavaram learning community.</small></div><div><GraduationCap/><b>LKG to 7th Class</b><small>English Medium education.</small></div><div><ShieldCheck/><b>Student-focused</b><small>Safety, values and participation.</small></div></div></div><div className="campus-card"><img src={d.campusImage||'/images/campus-original.jpeg'} alt="Sri Vidya E.M. School campus"/><div className="campus-overlay"><b>{SCHOOL.name}</b><span>Kesavaram • Est. 2002</span></div></div></div></section>
 <section id="principal" className="section principal-section"><SectionHead num="02" k={labels[lang].principal} teTitle={lang==='en'?'Leadership that keeps learning at the centre.':'విద్యార్థుల అభ్యాసాన్ని కేంద్రంగా ఉంచే నాయకత్వం.'}/><div className="principal-grid"><div className="principal-photo"><img src={d.principalImage||'/images/principal-designed.png'} alt={d.principalName||SCHOOL.principal}/><div className="principal-ribbon">PRINCIPAL • SRI VIDYA E.M. SCHOOL</div></div><div className="principal-copy"><span className="tag">SCHOOL LEADERSHIP</span><h3>{d.principalName||SCHOOL.principal}</h3><p>{d.principalMessage|| (lang==='en'?'Principal of Sri Vidya E.M. School. The website presents the school leadership with the official supplied photograph and school branding.':'శ్రీ విద్యా ఇ.ఎం. స్కూల్ ప్రధానోపాధ్యాయులు.')}</p><div className="name-board"><b>{d.principalName||SCHOOL.principal}</b><span>{d.principalRole||'Principal'}</span><small>Sri Vidya E.M. School</small></div><div className="principal-note">{lang==='en'?'Principal / Correspondent / Chairman':'ప్రధానోపాధ్యాయులు / కరస్పాండెంట్ / చైర్మన్'}</div></div></div></section>
 <section id="academics" className="section tinted"><SectionHead num="03" k={labels[lang].academics} teTitle={lang==='en'?'Clear learning stages from early years to upper primary.':'ప్రాథమిక దశ నుంచి ఉన్నత ప్రాథమిక స్థాయి వరకు స్పష్టమైన అభ్యాస దశలు.'}/><div className="card-grid">{d.academics.map((x,i)=><Feature item={x} i={i} key={i}/>)}</div></section>
 <section id="facilities" className="section"><SectionHead num="04" k={labels[lang].facilities} teTitle={lang==='en'?'Facilities designed around learning, safety and student experience.':'విద్య, భద్రత మరియు విద్యార్థి అనుభవం కోసం అందుబాటులో ఉన్న సౌకర్యాలు.'}/><div className="facility-grid">{d.facilities.map((x,i)=><VisualCard item={x} i={i} key={i}/>)}</div></section>
 <section id="activities" className="section tinted"><SectionHead num="05" k={labels[lang].activities} teTitle={lang==='en'?'Learning continues beyond the classroom.':'తరగతి గదిని దాటి కూడా అభ్యాసం కొనసాగుతుంది.'}/><div className="activity-grid">{d.activities.map((x,i)=><VisualCard item={x} i={i} key={i}/>)}</div></section>
 <section id="admissions" className="admission"><div><div className="eyebrow">{labels[lang].admissions}</div><h2>{lang==='en'?'Admissions enquiry for LKG to 7th Class':'LKG నుండి 7వ తరగతి వరకు అడ్మిషన్స్'}</h2><p>{lang==='en'?'English Medium • State Syllabus • School Bus + Van Available':'ఆంగ్ల మాధ్యమం • రాష్ట్ర సిలబస్ • స్కూల్ బస్ + వ్యాన్ అందుబాటులో ఉన్నాయి'}</p></div><a className="btn primary" href={'tel:'+(d.phone||SCHOOL.phone)}><Phone size={18}/> {lang==='en'?'Call for Enquiry':'వివరాలకు కాల్ చేయండి'}</a></section>
 <section className="section transport"><SectionHead num="06" k="TRANSPORT" teTitle={lang==='en'?'School Bus & Van Service':'స్కూల్ బస్ & వ్యాన్ సర్వీస్'}/><div className="transport-grid"><div className="transport-image"><Bus size={75}/><div><b>Bus Service</b><span>{d.busDetails||'School transport available.'}</span></div></div><div className="transport-image alt"><Bus size={75}/><div><b>Van Service</b><span>{d.vanDetails||'Van transport available.'}</span></div></div><div className="transport-copy"><h3>{d.transportTitle||'Convenient student transport'}</h3><p>{d.transportDesc||'School Bus and Van Services are available for students. Contact the school for current route and transport details.'}</p><a href="#contact" className="text-link">Contact school <ArrowRight size={16}/></a></div></div></section>
 <Gallery items={d.gallery} lang={lang}/>
 <section id="news" className="section news"><SectionHead num="08" k={labels[lang].news} teTitle={lang==='en'?'Official school news will appear here.':'అధికారిక పాఠశాల వార్తలు ఇక్కడ కనిపిస్తాయి.'}/>{d.news.length===0?<div className="empty-state"><Newspaper size={42}/><h3>{lang==='en'?'No news published yet':'ఇప్పటివరకు వార్తలు ప్రచురించలేదు'}</h3><p>{lang==='en'?'The school can add real news and events later through Admin CMS.':'అడ్మిన్ CMS ద్వారా నిజమైన వార్తలు మరియు కార్యక్రమాలను తరువాత జోడించవచ్చు.'}</p></div>:<div className="news-grid">{d.news.map((n,i)=><article key={i} className="news-card"><span>{n.date}</span><h3>{n.title}</h3><p>{n.description}</p></article>)}</div>}</section>
 <section id="contact" className="contact"><SectionHead num="09" k={labels[lang].contact} teTitle={lang==='en'?'Visit, call or email Sri Vidya E.M. School.':'శ్రీ విద్యా ఇ.ఎం. స్కూల్‌ను సందర్శించండి, కాల్ చేయండి లేదా ఇమెయిల్ చేయండి.'}/><div className="contact-grid"><div className="contact-info"><a href={'tel:'+(d.phone||SCHOOL.phone)}><Phone/><div><small>PHONE</small><b>{SCHOOL.phone}</b></div></a><a href={'mailto:'+(d.email||SCHOOL.email)}><Mail/><div><small>EMAIL</small><b>{d.email||SCHOOL.email}</b></div></a><div><MapPin/><div><small>ADDRESS</small><b>{d.address||SCHOOL.address}</b></div></div><div><Bus/><div><small>TRANSPORT</small><b>School Bus + Van Available</b></div></div></div><div className="map-card"><div className="map-pin"><MapPin size={30}/></div><h3>Kesavaram, West Godavari</h3><p>Ganapavaram Mandal, Andhra Pradesh - 534186</p><a className="btn primary" target="_blank" rel="noreferrer" href={d.mapsUrl||'https://www.google.com/maps/search/?api=1&query=Sri+Vidya+E.M.+School+Kesavaram+Andhra+Pradesh'}>Open Google Maps <ExternalLink size={15}/></a></div></div></section></main>
 <footer><div><strong>{SCHOOL.name}</strong><small>© {new Date().getFullYear()} • Established {SCHOOL.est} • Kesavaram</small></div><button className="admin-footer" onClick={()=>setAdmin(true)}><Settings size={13}/> Admin CMS</button></footer>{admin&&<Admin d={d} setD={setD} onClose={()=>setAdmin(false)}/>}<a className="floating-call" href={'tel:'+(d.phone||SCHOOL.phone)}><Phone/></a><a className="floating-top" href="#home">↑</a></>}
const root=document.getElementById('root');
createRoot(root).render(<ErrorBoundary><App/></ErrorBoundary>);
